Updated Quickstart
sustglobal/dev-center pull request #37
Opened 2022-04-01 17:26 UTC by jasSust

*In Quickstart guide table, changed Extreme Precipitation description from a probabilistic projection to annual days per year where precipitation exceeds 51mm.

2022-04-01 20:51 UTC, bcwaldon requested changes
One typo, I think

2022-04-01 20:51 UTC, bcwaldon commented on jekyll/userguide.md
> +We base our modeling of inland reverine flooding exposure on [recent advances](https://www.nature.com/articles/s41558-018-0257-z?WT.feed_name=subjects_hydrology) in combining climate models, hydrolog
should this be `riverine`?

2022-04-04 19:38 UTC, bcwaldon commented on jekyll/userguide.md
> +We base our modeling of inland reverine flooding exposure on [recent advances](https://www.nature.com/articles/s41558-018-0257-z?WT.feed_name=subjects_hydrology) in combining climate models, hydrolog
@jasSust ^

2022-04-11 00:51 UTC, jasSust commented on jekyll/userguide.md
> +We base our modeling of inland reverine flooding exposure on [recent advances](https://www.nature.com/articles/s41558-018-0257-z?WT.feed_name=subjects_hydrology) in combining climate models, hydrolog
Correct -- fixed

2022-04-11 01:05 UTC, jasSust commented
*Updated this PR with a number of typo fixes to the user guide

2022-04-11 16:00 UTC, merged